// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"github.com/didiegovieira/go-payments-core/apps/payments/internal/config"
	"github.com/didiegovieira/go-payments-core/apps/payments/internal/presentation/http"
)

// Injectors from wire.go:

// InitializeApp composes the payments API dependency graph.
func InitializeApp(settings config.Settings) *App {
	logger := NewLogger(settings)
	routerConfig := NewRouterConfig(settings)
	handler := http.NewRouter(routerConfig)
	server := NewHTTPServer(settings, handler)
	app := NewApp(settings, logger, server)
	return app
}
