DROP DATABASE IF EXISTS payments_db;
CREATE DATABASE payments_db;

DROP DATABASE IF EXISTS audit_db;
CREATE DATABASE audit_db;

DROP DATABASE IF EXISTS fraud_db;
CREATE DATABASE fraud_db;

DROP DATABASE IF EXISTS notifications_db;
CREATE DATABASE notifications_db;