// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/didiegovieira/go-payments-core/apps/notifications/internal/application"
	"github.com/didiegovieira/go-payments-core/apps/notifications/internal/infrastructure/messaging"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeWorker() (*messaging.Application, func(), error) {
	logger := provideLogger()
	tracer := provideTracer()
	app := &application.App{
		Logger: logger,
		Tracer: tracer,
	}
	messagingApplication := &messaging.Application{
		BaseApp: app,
	}
	return messagingApplication, func() {
	}, nil
}

// wire.go:

var wireWorkerSet = wire.NewSet(
	wireCommonSet,
	wire.Struct(new(messaging.Application), "*"),
)
