// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/didiegovieira/go-payments-core/apps/payments/internal/application"
	"github.com/didiegovieira/go-payments-core/apps/payments/internal/infrastructure/api"
	"github.com/didiegovieira/go-payments-core/apps/payments/internal/infrastructure/api/handler"
	"github.com/didiegovieira/go-payments-core/apps/payments/internal/test"
	"github.com/google/wire"
	"go.uber.org/mock/gomock"
)

// Injectors from wire.go:

func InitializeApi() (*api.Application, func(), error) {
	logger := provideLogger()
	tracer := provideTracer()
	app := &application.App{
		Logger: logger,
		Tracer: tracer,
	}
	server := provideHttpServer()
	apiServer := provideGinServer(server)
	presenter := providePresenter()
	health := &handler.Health{
		Presenter: presenter,
	}
	apiApplication := &api.Application{
		BaseApp:       app,
		Server:        apiServer,
		HealthHandler: health,
	}
	return apiApplication, func() {
	}, nil
}

func InitilizeTests(mockCtrl *gomock.Controller) (*test.Application, func(), error) {
	logger := provideLogger()
	tracer := provideTracer()
	app := &application.App{
		Logger: logger,
		Tracer: tracer,
	}
	server := provideHttpServer()
	apiServer := provideGinServer(server)
	presenter := providePresenter()
	health := &handler.Health{
		Presenter: presenter,
	}
	apiApplication := &api.Application{
		BaseApp:       app,
		Server:        apiServer,
		HealthHandler: health,
	}
	testApplication := &test.Application{
		BaseApp:  app,
		Api:      apiApplication,
		MockCtrl: mockCtrl,
	}
	return testApplication, func() {
	}, nil
}

// wire.go:

var wireApiSet = wire.NewSet(
	wireCommonSet,
	wireUsecaseSet,
	wireMiddlewareSet,
	wireHandlerSet,
	wireServerSet, wire.Struct(new(api.Application), "*"),
)

var wireTestSet = wire.NewSet(
	wireCommonSet,
	wireUsecaseSet,
	wireMiddlewareSet,
	wireHandlerSet,
	wireServerSet, wire.Struct(new(api.Application), "*"), wire.Struct(new(test.Application), "*"),
)
