// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/didiegovieira/go-payments-core/apps/payments/internal/application"
	"github.com/didiegovieira/go-payments-core/apps/payments/internal/application/usecase/payment"
	"github.com/didiegovieira/go-payments-core/apps/payments/internal/application/usecase/wallet"
	"github.com/didiegovieira/go-payments-core/apps/payments/internal/infrastructure/api"
	"github.com/didiegovieira/go-payments-core/apps/payments/internal/infrastructure/api/handler"
	payment2 "github.com/didiegovieira/go-payments-core/apps/payments/internal/infrastructure/api/handler/payment"
	wallet2 "github.com/didiegovieira/go-payments-core/apps/payments/internal/infrastructure/api/handler/wallet"
	"github.com/didiegovieira/go-payments-core/apps/payments/internal/infrastructure/api/middleware"
	"github.com/didiegovieira/go-payments-core/apps/payments/internal/test"
	"github.com/google/wire"
	"go.uber.org/mock/gomock"
)

// Injectors from wire.go:

func InitializeApi() (*api.Application, func(), error) {
	logger := provideLogger()
	tracer := provideTracer()
	app := &application.App{
		Logger: logger,
		Tracer: tracer,
	}
	server := provideHttpServer()
	apiServer := provideGinServer(server)
	presenter := providePresenter()
	cors := &middleware.Cors{
		Presenter: presenter,
	}
	health := &handler.Health{
		Presenter: presenter,
	}
	create := payment.NewCreate()
	paymentCreate := &payment2.Create{
		Presenter:     presenter,
		CreateUseCase: create,
	}
	walletCreate := wallet.NewCreate()
	create2 := &wallet2.Create{
		Presenter:     presenter,
		CreateUseCase: walletCreate,
	}
	apiApplication := &api.Application{
		BaseApp:              app,
		Server:               apiServer,
		CorsMiddleware:       cors,
		HealthHandler:        health,
		PaymentCreateHandler: paymentCreate,
		WalletCreateHandler:  create2,
	}
	return apiApplication, func() {
	}, nil
}

func InitializeTests(mockCtrl *gomock.Controller) (*test.Application, func(), error) {
	logger := provideLogger()
	tracer := provideTracer()
	app := &application.App{
		Logger: logger,
		Tracer: tracer,
	}
	server := provideHttpServer()
	apiServer := provideGinServer(server)
	presenter := providePresenter()
	cors := &middleware.Cors{
		Presenter: presenter,
	}
	health := &handler.Health{
		Presenter: presenter,
	}
	create := payment.NewCreate()
	paymentCreate := &payment2.Create{
		Presenter:     presenter,
		CreateUseCase: create,
	}
	walletCreate := wallet.NewCreate()
	create2 := &wallet2.Create{
		Presenter:     presenter,
		CreateUseCase: walletCreate,
	}
	apiApplication := &api.Application{
		BaseApp:              app,
		Server:               apiServer,
		CorsMiddleware:       cors,
		HealthHandler:        health,
		PaymentCreateHandler: paymentCreate,
		WalletCreateHandler:  create2,
	}
	testApplication := &test.Application{
		BaseApp:  app,
		Api:      apiApplication,
		MockCtrl: mockCtrl,
	}
	return testApplication, func() {
	}, nil
}

// wire.go:

var wireApiSet = wire.NewSet(
	wireCommonSet,
	wireUsecaseSet,
	wireMiddlewareSet,
	wireHandlerSet,
	wireServerSet, wire.Struct(new(api.Application), "*"),
)

var wireTestSet = wire.NewSet(
	wireCommonSet,
	wireUsecaseSet,
	wireMiddlewareSet,
	wireHandlerSet,
	wireServerSet, wire.Struct(new(api.Application), "*"), wire.Struct(new(test.Application), "*"),
)
